
import type { Therapist, SimulationScenario } from './types';

export const THERAPISTS_DATA: Therapist[] = [
  {
    id: '1',
    name: 'Dra. Ana García',
    photoUrl: 'https://picsum.photos/seed/therapist1/200/200',
    rating: 4.9,
    reviewsCount: 85,
    specialties: ['Ansiedad', 'Depresión', 'Terapia de Pareja'],
    pricePerSession: 50,
    languages: ['Español', 'Inglés'],
    verified: true,
    credentials: 'Lic. en Psicología, Univ. de Buenos Aires. Mat. 12345',
    bio: 'Con más de 10 años de experiencia, mi enfoque se centra en la terapia cognitivo-conductual para ayudarte a superar tus desafíos.',
    email: '',
    whatsapp: '',
    published: true,
    userId: ''
  },
  {
    id: '2',
    name: 'Dr. Carlos Rodríguez',
    photoUrl: 'https://picsum.photos/seed/therapist2/200/200',
    rating: 4.8,
    reviewsCount: 72,
    specialties: ['Estrés', 'Adicciones', 'Autoestima'],
    pricePerSession: 55,
    languages: ['Español'],
    verified: true,
    credentials: 'Psicólogo Clínico, Univ. Nacional de Colombia. Reg. 67890',
    bio: 'Especialista en terapia humanista y mindfulness. Juntos encontraremos las herramientas para tu bienestar emocional.',
    email: '',
    whatsapp: '',
    published: true,
    userId: ''
  },
  {
    id: '3',
    name: 'Dra. Sofía Martínez',
    photoUrl: 'https://picsum.photos/seed/therapist3/200/200',
    rating: 4.9,
    reviewsCount: 91,
    specialties: ['Terapia Familiar', 'Trastornos Alimenticios', 'Ansiedad'],
    pricePerSession: 60,
    languages: ['Español', 'Catalán'],
    verified: true,
    credentials: 'Dra. en Psicología, Univ. de Barcelona. Col. 10112',
    bio: 'Mi objetivo es crear un espacio seguro para explorar dinámicas familiares y personales, promoviendo la comunicación y el cambio.',
    email: '',
    whatsapp: '',
    published: true,
    userId: ''
  },
  {
    id: '4',
    name: 'Dr. Javier López',
    photoUrl: 'https://picsum.photos/seed/therapist4/200/200',
    rating: 4.7,
    reviewsCount: 65,
    specialties: ['Depresión', 'Duelo', 'Crecimiento Personal'],
    pricePerSession: 45,
    languages: ['Español', 'Inglés'],
    verified: false,
    credentials: 'Máster en Psicoanálisis, Univ. Complutense de Madrid. Colegiado 13145',
    bio: 'A través de la escucha activa, te acompañaré en el proceso de entender y sanar tus heridas emocionales.',
    email: '',
    whatsapp: '',
    published: true,
    userId: ''
  },
  {
    id: '5',
    name: 'Dra. Laura Fernández',
    photoUrl: 'https://picsum.photos/seed/therapist5/200/200',
    rating: 5.0,
    reviewsCount: 112,
    specialties: ['Terapia de Pareja', 'Sexualidad', 'Comunicación'],
    pricePerSession: 70,
    languages: ['Español'],
    verified: true,
    credentials: 'Especialista en Terapia Sistémica, ITAD. Mat. 15161',
    bio: 'Apasionada por ayudar a las parejas a construir relaciones más fuertes, saludables y satisfactorias.',
    email: '',
    whatsapp: '',
    published: true,
    userId: ''
  },
  {
    id: '6',
    name: 'Dr. David Pérez',
    photoUrl: 'https://picsum.photos/seed/therapist6/200/200',
    rating: 4.8,
    reviewsCount: 88,
    specialties: ['Ansiedad', 'Fobias', 'TOC'],
    pricePerSession: 52,
    languages: ['Español', 'Inglés', 'Francés'],
    verified: true,
    credentials: 'Psicólogo Sanitario, Univ. de Valencia. CV-17181',
    bio: 'Utilizo técnicas de exposición y prevención de respuesta para ayudarte a recuperar el control sobre la ansiedad y tus miedos.',
    email: '',
    whatsapp: '',
    published: true,
    userId: ''
  },
];


export const SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    id: 'scenario-1',
    title: 'Poner un Límite a un Familiar',
    description: 'Practica una conversación para establecer un límite saludable con un miembro de tu familia que te pide demasiado.',
    category: 'Relaciones',
    personaPrompt: "Actúa como un familiar cercano (ej. madre, hermano) que está acostumbrado a que el usuario siempre ceda. Eres cariñoso/a, pero tiendes a la manipulación emocional sutil. Cuando el usuario intente poner un límite, reacciona con sorpresa y algo de victimismo, como 'No puedo creer que no me ayudes con esto, con todo lo que he hecho por ti'. Tu objetivo es hacer que el usuario se sienta culpable, pero si es firme y claro, muestra gradualmente comprensión.",
  },
  {
    id: 'scenario-2',
    title: 'Pedir un Aumento de Sueldo',
    description: 'Simula una reunión con tu jefe/a para negociar un aumento de sueldo basado en tus logros y responsabilidades.',
    category: 'Trabajo',
    personaPrompt: "Actúa como un/a jefe/a ocupado/a, directo/a pero justo/a. Valoras los datos y los resultados concretos. Al principio de la conversación, muestra escepticismo y menciona las restricciones presupuestarias de la empresa. Si el usuario es vago o emocional, pide datos específicos ('¿Puedes darme ejemplos de cómo has superado tus objetivos?'). Si presenta argumentos sólidos y demuestra su valor, muéstrate progresivamente más receptivo/a y abierto/a a la negociación.",
  },
  {
    id: 'scenario-3',
    title: 'Hablar de tus Sentimientos con tu Pareja',
    description: 'Ensaya cómo abrir una conversación vulnerable con tu pareja sobre algo que te ha estado molestando.',
    category: 'Relaciones',
    personaPrompt: "Actúa como una pareja que quiere lo mejor para la relación pero que se pone a la defensiva fácilmente. Cuando el usuario empiece a hablar de sus sentimientos, tu primera reacción es pensar que es una crítica hacia ti ('¿Así que estás diciendo que es mi culpa?'). Si el usuario utiliza frases en primera persona ('Yo siento que...') y evita culpar, baja la guardia gradualmente y muestra curiosidad y empatía ('No me había dado cuenta de que te sentías así. Cuéntame más').",
  },
  {
    id: 'scenario-4',
    title: 'Manejar una Crítica Injusta',
    description: 'Aprende a responder de manera asertiva y calmada cuando un amigo/a te hace una crítica que consideras injusta.',
    category: 'Social',
    personaPrompt: "Actúa como un/a amigo/a bienintencionado/a pero algo torpe socialmente, que acaba de hacer un comentario crítico disfrazado de consejo ('Solo digo que quizás deberías esforzarte más, es por tu bien'). No ves tu comentario como un ataque. Si el usuario se enfada o se pone a la defensiva, reacciona con confusión ('¡Oye, solo intentaba ayudar!'). Si el usuario responde asertivamente, validando tu intención pero explicando cómo le hizo sentir tu comentario ('Aprecio que te preocupes, pero la forma en que lo dijiste me dolió'), discúlpate y muestra arrepentimiento.",
  },
  {
    id: 'scenario-5',
    title: 'Decir "No" a un Compromiso Social',
    description: 'Practica cómo declinar una invitación de un amigo sin sentirte culpable y sin dañar la relación.',
    category: 'Social',
    personaPrompt: "Actúa como un/a amigo/a muy extrovertido/a y entusiasta que está organizando un evento. Eres muy persuasivo/a. Cuando el usuario intente decir que no, insiste un poco ('¡Vamos, será divertido! ¡Todo el mundo irá!'). No aceptas un 'no' vago fácilmente. Si el usuario es claro, firme y honesto pero amable ('Te lo agradezco mucho, pero necesito ese tiempo para recargar energías'), respeta su decisión y responde con comprensión ('¡Claro, lo entiendo! Nos vemos en la próxima').",
  },
  {
    id: 'scenario-6',
    title: 'Dar Feedback Constructivo a un Colega',
    description: 'Simula cómo darle a un compañero de trabajo una retroalimentación sobre un aspecto de su trabajo que está afectando al equipo.',
    category: 'Trabajo',
    personaPrompt: "Actúa como un/a colega de trabajo que generalmente es amigable pero sensible a la crítica sobre su desempeño. Cuando el usuario comience a darte feedback, reacciona con una actitud defensiva y justificativa ('Bueno, es que he estado muy ocupado', 'Nadie me explicó bien cómo hacerlo'). Tu objetivo es desviar la responsabilidad. Sin embargo, si el usuario utiliza la técnica del 'sándwich' (positivo-negativo-positivo) y se enfoca en el comportamiento y no en la persona, gradualmente acepta el feedback y muéstrate dispuesto/a a colaborar para encontrar una solución.",
  },
];
